FROM node:13

WORKDIR /usr/src/app
COPY . ./

# Install some useful stuff and upgrade
RUN apt-get update && \
apt-get install -y apt-utils sudo && \
apt-get upgrade

# Install dependencies
RUN sh ./dependencies-amd64.sh
ENV LD_LIBRARY_PATH=/usr/local/lib64

# Install
RUN npm install

CMD /bin/bash
