version: 2
jobs:
  build-yash-job:
    docker:
      - image: circleci/node:13
      
    environment:
      LD_LIBRARY_PATH: /usr/local/lib64

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: cd ./yash && sudo chmod +x ./dependencies-amd64.sh && sudo ./dependencies-amd64.sh

      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yash/package.json" }}

      - run:
          name: Install
          command: cd ./yash && npm install

      # - save_cache:
      #     key: dependency-cache-{{ checksum "yash/package.json" }}
      #     paths:
      #       - ./yash/node_modules

      - run:
          name: Run Unit Tests
          command: cd ./yash && npm test

      - store_artifacts:
          path: yash/test/results/test-results.xml

      - store_test_results:
          path: yash/test/results

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .git
            - deploy-to-resin.sh

  deploy-job:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy to Resin.io
          command: chmod +x ./deploy-to-resin.sh && ./deploy-to-resin.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-yash-job

      - deploy-job:
          requires:
            - build-yash-job
          filters:
            branches:
              only: master
