version: 2
jobs:
  build-yash-job:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo/yash

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: chmod +x ./dependencies-amd64.sh && ./dependencies-amd64.sh

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm install --dev --unsafe-perm && npm cache clean && rm -rf /tmp/*

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Run Unit Tests
          command: npm test

      - store_artifacts:
          path: test/results/test-results.xml

      - store_test_results:
          path: test/results

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .git
            - deploy-to-resin.sh

  deploy-job:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy to Resin.io
          command: chmod +x ./deploy-to-resin.sh && ./deploy-to-resin.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-yash-job

      - deploy-job:
          requires:
            - build-yash-job
          filters:
            branches:
              only: master
