version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: chmod +x ./dependencies-amd64.sh && ./dependencies-amd64.sh

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm install --dev --unsafe-perm && npm cache clean && rm -rf /tmp/*

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Run Unit Tests
          command: npm test

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_test_results:
          path: tests